name: Setup Fastlane Environment
description: Sets up Ruby, installs Bundler, and provides a Fastfile.
author: DigitalDementia
inputs:
  ruby-version:
    description: Ruby version to use
    required: false
    default: 3.3
  working-directory: 
    description: The working directory of the calling repository
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true

    - name: Install Fastlane and other Gem dependencies
      run: |
        cp $GITHUB_ACTION_PATH/Gemfile ${{ inputs.working-directory }}/Gemfile
        bundle config set path 'vendor/bundle'
        bundle install --gemfile ${{ inputs.working-directory }}/Gemfile
      shell: bash

    - name: Copy the Fastfile and custom lanes and actions
      run: |      
        mkdir -p ${{ inputs.working-directory }}/fastlane
        rsync -av --delete $GITHUB_ACTION_PATH/fastlane/ ${{ inputs.working-directory }}/fastlane
      shell: bash
